name: Lobby-System
main: me.chaotisch3r.lobby.Lobby
version: 1.0
author: Chaotisch3r
api-version: 1.13
commands:
  build:
    description: This command contains to the Lobby-System.
    permissions: [ lobby.*, lobby.build ]
  language:
    description: This command contains to the Lobby-System.
    permissions: [ lobby.*, lobby.language ]
    aliases: [ lang ]
  world:
    description: This command contains to the Lobby-System.
    permissions: [ lobby.*, lobby.world ]
  warp:
    description: This command contains to the Lobby-System.
    permissions: [ lobby.*, lobby.warp ]
  lobby:
    description: This command contains to the Lobby-System.
    permissions: [ lobby.*, lobby.setup ]
  ping:
    description: This command contains to the Lobby-System.
    permissions: [ lobby.*, lobby.ping ]
  rank:
    description: This command contais to the Lobby-System.
    permissions: [ lobby.*, lobby.rank ]
  coins:
    description: This Command contains to the Lobby-System.
    permissions: [ lobby.*, lobby.coins ]
    aliases: [ coin ]